### ISSUE TITLE
Implement Copy Functionality

### ISSUE THREAD

**Issue by dschoen** [dschoen/mobilequiz#12]
Implement the functionality of the Copy function.

When a quiz is copied, title, questions and choices should be copied as well. But the answers should not be copied.

**Comment by niranjanbasnet** [comment]
Hey Daniel,

Can I try this one after I do the QR page customization?

With Regards

**Comment by dschoen** [comment]
Sure,

gor for it!

I don't know if we discussed it last time, but I won't be able to meet 
tomorrow, as I have appointments, workshops and business travelings all 
over the next week :-/

Greetings,
     Daniel

PS: How were your exams?

Am 17.06.2016 um 19:07 schrieb niranjanbasnet:

**Comment by niranjanbasnet** [comment]
We were not able to discuss it last time. In last meeting we discussed about the QR page and logo of application. I was out in sort of small vacation after my exams.

My exams went well. I hope professor will be able to judge me for my actual performance. :) Lets keep up the high motive. 

I am working on logo and QR page this week. Then perform manual testing on the beta version for 0.9 release. Lets hope for the best.
