### ISSUE TITLE
All Grammatical, spelling and semantic issues

### ISSUE THREAD

**Issue by niranjanbasnet** [dschoen/mobilequiz#20]
[Grammatical and spelling Issues]
1. When status of the current round changed then it gives semantically false statement. Need to be changed from "The status of the round is successful changed." to "The status of this round is successfully changed."
2. When certain round is deleted regardless of status then the prompt message must be changed. "successful deleted" to "Successfully deleted"
3. The table header name of "Choose round to show results:" must be changed. " Startdate " to "Start date"

[Semantic Issues]

**Comment by dschoen** [comment]
done
