### ISSUE TITLE
Title numeric text box functionality

### ISSUE THREAD

**Issue by niranjanbasnet** [dschoen/mobilequiz#21]
1. Get quiz with question answering numerical values
2. Do the given example question

For example: 
If question is "What is 4+2" then correct answer is "6". 
Now setting up the question parameters
Minimum: 1
Max: 100
Step Range: 2
Correct Value:6
Tolerance: 0
1. Now when you open the current quiz round when answering the question with typing it on numeric box on left side of slider.
2. Put 3 on it and move the slider it will give "5 " on the next step which should not happen.
   Possible Scenarios:
3. Users will not be able to give correct answer as user uses slider afterwards.
4. User may not be aware if he/she uses both at same time.

Resolving Measure:
This issue must be resolved by either disabling the numerical text box or we must be able to maintain the relation ship between Maximum and minimum.

**Comment by dschoen** [comment]
Cannot reproduce this with firefox. Textbox always jumps to higher, valid value.
