### ISSUE TITLE
Create new fancy stilysh Icon

### ISSUE THREAD

**Issue by dschoen** [dschoen/mobilequiz#6]
Create a new and stylish ICON.svg for the plugin.

**Comment by niranjanbasnet** [comment]
Created 2 possible icons. Waiting for confirmation with supervisor.

**Comment by niranjanbasnet** [comment]
Made Custom icon for Mobile Quiz. Waiting for final verification.

**Comment by niranjanbasnet** [comment]
Will customize it further with chosen icon.

**Comment by niranjanbasnet** [comment]
Done but waiting for confirmation.
